### ISSUE TITLE
Provide a way to subscribe to changes globally

### ISSUE THREAD

**Issue by smikula** [mweststrate/mobservable#108]
It would be helpful if there were a way to register a global listener that is notified of _any_ change to _any_ object.  For instance, this would be useful to efficiently trace state changes.  Or in my case, I'm trying to use mobservable in a more structured, Redux-like data flow and I'd like to detect if anyone tries to modify the state outside of the proscribed pattern.

Currently it's possible to achieve this by using an autorun() in which you serialize the entire state tree.  However, you'll end up examining the whole state every time it is changed, which gets prohibitively expensive as the app gets more complex.  Obviously mobservable knows internally when every change happens, but right now (as far as I can tell) there's know way for me to subscribe to all such events.

**Comment by mweststrate** [comment]
Hi @smikula,

The simplest way to achieve that is to use `autorun(() => mobservable.toJSON(myTree))` (which will also work for cyclic structures btw). However for _large_ state trees that is indeed quite inefficient, in such cases [`createTransformer`](http://mweststrate.github.io/mobservable/refguide/create-transformer.html) comes in handy. Effectively it can be used to create a lot of small 'autoruns' that memoize so that they don't need to re-run on objects that didn't change. See for an example of serializing the state tree using `createTransformer` this [example](https://github.com/mweststrate/mobservable-reactive2015-demo/blob/master/src/stores/domain-state.js#L46).

I have some ideas on building a small abstraction layer on top of mobservable which implements a lot of these standard flux / redux functions in an standardized way so that you get them really out-of-the-box.

**Comment by mweststrate** [comment]
Closed for inactivity, feel free to re-open at any time.
