### ISSUE TITLE
Deleting a key from a map does not unobserve calculated values first

### ISSUE THREAD

**Issue by tcrognon** [mweststrate/mobservable#119]
When deleting a key from a map, if the value at that key is an object that has a calculated property with the said object as a dependency, the calculation executes after the object is undefined, which throws an error.
```
import {observable, map, autorun} from 'mobservable';
const myObservable = observable({
    myMap: map()
});
myObservable.myMap.set('myId', {
    myProp: 'myPropValue',
    myCalculatedProp: () => {
        return myObservable.myMap.get('myId').myProp + ' calculated';
    }
});
// the error only happens if the value is observed
autorun(() => {
    console.log(myObservable.myMap.get('myId').myCalculatedProp);
});
myObservable.myMap.delete('myId');

/*[mobservable.view '.myId.myCalculatedProp'] There was an uncaught error during the computation of ComputedObservable[.myId.myCalculatedProp (current value:'myPropValue calculated')] function myCalculatedProp() {
        return myObservable.myMap.get('myId').myProp + ' calculated';
    }*/

/*Uncaught TypeError: Cannot read property 'myProp' of undefined*/
```

Since myCalculatedProp is no longer observable after its parent object is deleted from the map, shouldn't it be expected that it won't execute?

**Comment by tcrognon** [comment]
Sorry, the autorun should be this. Same error, of course.

```
autorun(() => {
    myObservable.myMap.values().forEach(value => {
        console.log(value.myCalculatedProp);
    });
});
```

**Comment by mweststrate** [comment]
Thanks, gonna look into this to see whether this is a preventable situation. Note btw that using `return this.myProp + ' calculated'` or first calling `map.has('myId')` will both solve the situation.

**Comment by tcrognon** [comment]
Yes, I solved it by using .has() already. It's not a big deal since the workaround is so easy.

I posted this because my app has a lot of calculated properties. I have a lot of interrelated stores and use calculated properties to essentially cache things that are multiple hops away from whatever object I happen to have at hand. Having to check whether an object has been deleted from the store in every calculated property adds clutter and conceptually there's no reason to, so I thought I'd post here.

Thank you, btw, for making mobservable. I'm moving my app from redux and it's been really great.

**Comment by mweststrate** [comment]
I thought about this one but I think its behavior is correct:
1. the observable expression cannot be cleaned up immediately after removing the object, because you could have references to the same object anywhere in your app, so the expression is potentially still used.
2. In your example the expression is actually still marked as in use, namely by the `autorun`.
3. Once the `autorun` run's, it will detect that it was previously using your expression but not anymore (since the key has disappeared from the collection), so that is the moment the expression is cleaned up.
4. However, before that `autorun` the calculated expression is evaluated once, because mobservable tries to evaluate any dependent expression before running the `autorun`, to avoid the autorun from running with stale values. The expression is re-evaluated because the map itself changed, so it's value is indeed no longer correct.

This might not be relevant for your real case, but note that in your specific example you could solve it by using `this`. In general, if your object A has a computed property that depends on another object B which is always the same one, you can also just store a reference to that object B on your object A to avoid the map lookup.

In general you need a lot less maps when you migrate from Redux to Mobservable. Most collection I have just store stuff in observable arrays instead of maps because I hardly need lookups; you can just make real references to other objects in the constructor or after creation. Since you don't need to normalize the data, a lot of lookup caches will disappear.

**Comment by tcrognon** [comment]
I'm convinced, thank you. Using `this` works for the majority of my use cases, that's a great suggestion and something I should've done from the start. I have to use a regular function instead of fat arrow, of course. I'm fairly new to JS still. Here is the updated, working example code if anyone reading this is interested:

```
import {observable, map, autorun} from 'mobservable';
const myObservable = observable({
    myMap: map()
});
myObservable.myMap.set('myId', {
    myProp: 'myPropValue',
    myCalculatedProp: function () {
        return this.myProp + ' calculated';
    }
});
// the error only happens if the value is observed
autorun(() => {
    myObservable.myMap.values().forEach(value => {
        console.log(value.myCalculatedProp);
    });
});
myObservable.myMap.delete('myId');

```

I can't see a way to not use maps for my use case, but could be totally wrong. I hope to see mobservable (rivlets?) at a conference in the future or catch you in a more QA format somewhere so I can learn.

**Comment by mweststrate** [comment]
I'll be speaking at React Amsterdam conference in april. So feel free to join. Tickets are still available :)
