### ISSUE TITLE
ES6 Class Definitions

### ISSUE THREAD

**Issue by dschalk** [mweststrate/mobservable#14]
I noticed in the examples that you use ES6 syntax for everything short of defining React classes. I revised the todo example to use ES6 syntax for everything. One advantage is that I was able to leave the react 'props' object empty in class 'ToList' and substitute 'this store' for 'this.props.store' in the two function definitions. The last three lines of the file are:
```javascript
let TodoView = mobservable.reactiveComponent(ToView); 
let TodoList = mobservable.reactiveComponent(ToList);
React.render(<TodoList />, document.getElementById('approot'));
```
React 'props' creation was still very useful in creating ToView components on the fly.
Maybe it would be a good idea to include some examples that not only use ES6 syntax for most things, but also use it to create classes by extending React.Component. If you like, I will make a pull request to include the following example along with package.json and webpack-config.js files so a user could get up and running with 'npm install', 'webpack', and whatever web server they like. I could add webpack-dev-server. I have 'warp' globally install so wherever there is an index.html file, the command 'warp' loads in on port 3000. 'ALT backtick right arrow' on the keyboard followed by 'CTL R' shows me a reloaded webpage. 'ALT backtick right arrow' again takes me back to my 'lilyterm' terminal. I don't feel any pressing need to start using automatic web page reloading again. 
Here is my proposed ES6 version of the todo file:
```javascript
import mobservable from 'mobservable';
import React from 'react';
var todoStore = mobservable.makeReactive({
    todos: [
        {
            title: 'Find a clean mug',
            completed: true
        },
        {
            title: 'Make coffee',
            completed: false
        }
    ],
    completedCount: function() {
        return this.todos.filter((todo) => todo.completed).length;
    },
    pending: 0
});

todoStore.addTodo = (title) => {
    todoStore.todos.push({
        title: title,
        completed: false
    });
};

todoStore.removeTodo = (todo) => {
    todoStore.todos.splice(todoStore.todos.indexOf(todo), 1);
};

todoStore.loadTodosAsync = () => {
    todoStore.pending++;
    setTimeout(function() {
        todoStore.addTodo('Asynchronously created todo');
        todoStore.pending--;
    }, 2000);
};

class ToList extends React.Component{
  constructor(props) {
    super(props);
    this.store = todoStore;
  }
    render = () => {
        var store = this.store;
        return (<div>
            <ul>
                { store.todos.map((item, idx) =>
                    (<TodoView store={ store } todo={ item } key={ idx } />)
                ) }
                { store.pending ? (<li>Loading more items...</li>) : null }
            </ul>
            <hr/>
            Completed { store.completedCount } of { store.todos.length } items.<br/>
            <button onClick={ this.onNewTodo }>New Todo</button>
            <button onClick={ this.loadMore }>Load more...</button>
        </div>);
    }

    onNewTodo = () => {
        this.store.addTodo(prompt('Enter a new todo:', 'Try mobservable at home!'));
    }

    loadMore = () => {
        this.store.loadTodosAsync();
    }
};

class ToView extends React.Component{
    render = () => {
        var todo = this.props.todo;
        return (<li>
            <input type='checkbox' checked={ todo.completed } onChange={ this.onToggleCompleted } />
            {todo.title}{' '}
            <a href='#' onClick={ this.onEdit }>[edit]</a>
            <a href='#' onClick={ this.onRemove }>[remove]</a>
        </li>);
    }

    onToggleCompleted = () => {
        this.props.todo.completed = !this.props.todo.completed;
    }

    onEdit = (e) => {
        e.preventDefault();
        this.props.todo.title = prompt('Todo:', this.props.todo.title);
    }

    onRemove = (e) => {
        e.preventDefault();
        this.props.store.removeTodo(this.props.todo);
    }
};
let TodoView = mobservable.reactiveComponent(ToView); 
let TodoList = mobservable.reactiveComponent(ToList);
React.render(<TodoList />, document.getElementById('approot'));
```

**Comment by mweststrate** [comment]
Hi @dschalk,

thanks for the suggestion! There is a simple getting started project that bundles the todo list code in a webpack here: https://github.com/mweststrate/react-mobservable-boilerplate

As you can see in its change log, I have been quite searching whether to express the example in ES5 or ES6. On one hand I wanted to use ES6 because it is convenient, but on the other hand I didn't want to expose constructions that might be alien to people not comfortable with ES6 yet. So thats why I ended up with a mix that uses the old createClass (to avoid binding issues) but also some ES6 constructions like arrow functions and imports (I guess anyone will understand at least what the syntax means).

But I get this question more, so I think I'm gonna extend the api documentation with some example code that is flavored in both ES5, ES6 and TS.

I really like your binding alternative, I thought that wasn't possible yet in ES6, so I'm gonna definitely use that. 

Just an idea: maybe it is fun to expose different branches of the boilerplate project, one for ES5, and one for full ES6, so that people can choose.

Apologies for the late reply btw, I was sort of on holiday ;) Thanks for thinking along!

**Comment by mweststrate** [comment]
Hi David,

I've added some possible syntax examples to the docs:
https://github.com/mweststrate/mobservable/blob/master/docs/syntax.md
and 
https://github.com/mweststrate/mobservable/blob/master/docs/api.md#reactivecomponentcomponent

I hope that suffices for most people.

Thanks for the feedback,

Michel.
