### ISSUE TITLE
Move most of the docs to mweststrate.github.io/mobservable

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/mobservable#7]
Clean up and move readme, improve / more examples. Possible pages:

* about
* getting started
* blog
* reference: api
* reference: advanced api & optimizations
* examples
* faq (with flux comparison for example)
* tricks & tips

**Comment by mweststrate** [comment]
Docs are extended a lot. 
What's left: tricks & tips and examples for specific scenarios.

**Comment by mweststrate** [comment]
New docs are now available at https://mweststrate.github.io/mobservable/

**Comment by dschalk** [comment]
I am continuing to document the transition of my Game of Score project over to Mobservable at [Tutorial](https://www.fpcomplete.com/user/dschalk/Websockets%20Game%20of%20Score). Lately, I have been playing with the monads I tweeted about. I am treating mobservable reactive primitives like black box abstractions and superimposing the monad functions "bind" and "return" on them. I have been surprised by the flexibility of my inventions. They can bind to multi-argument functions and, it turns out, to other mobservable reactive primitives. "bind" takes a function as an argument and runs the function on the value of the reactive entity that calls it. If the function happens to be a reactive primitive, running it on the value of the calling reactive primitive give it the value of the calling reactive primitive.  In other words, m1.bnd(m2) results in m1() === m2(). That is pleasing but trivial. More sophisticated things can be done with multiple arguments and chaining.

Next, I am going to see what can be done with reactive objects, arrays, and after that, perhaps - this is hard to imagine - reactive function monads.  

My reactive monad investigations are just an amusing diversion. Just play at this point, and probably forever. But it would be extra fun to find a legitimate use for them in an application or library. Do you think that could ever happen, or will there always be more efficient ways to accomplish what the monads can do?

**Comment by mweststrate** [comment]
Hmm.. hard to tell, efficiency isn't a big issue here, but the concept of monads themselves are still under the law of crockford, so I'm not sure whether people without a haskell background will resort to them quickly (explicitly). But it is cool it fits in anyway :)
