### ISSUE TITLE
advice for efficient selection change tracking

### ISSUE THREAD

**Issue by Kosta-Github** [mweststrate/mobservable#93]
Suppose you have several `immutable` items with unique IDs and I would like to efficiently track a single selection scenario of them without requiring to add an `isSelected` property to each item (since the items are `immutable`). The items are displayed as `cards` in a `React` UI. By efficient, I mean, only the `card` of the `selected` or `unselected` item should be updated, not all others.

I first tried something like this:
```JavaScript
const selectedItem = mobs.obervable('');

const setSelectedItem = (id = '') => { selectedItem(id); }
const isSelectedItem = (id) => { return (selectedItem() === id); }
```
and then used the `isSelectedItem(id)` within a `mobs.observer` decorated `React` component for each of the items.

The problem is, that the `isSelectedItem(id)` __fires__ on each change of `selectedItem` for __all__ item `cards`, selected or not.

I would like to have a mechanism to turn the `isSelectedItem(id)` observable to only __fire__ if there is an actual change for the __returned value__, not each time the `selectedItem` changes.

Maybe there is already a simple mechanism for this, I haven't found so far?

**Comment by Kosta-Github** [comment]
Actually, what I am asking for is more or less the same optimization you do when assigning the same value to an `observable` that you don't trigger an `update` event. The same should be true for derived values, IMHO: if the derived value doesn't change the derived value shouldn't trigger an update event either...

**Comment by mweststrate** [comment]
to answer your first question, the solution to that is to generate observables on the fly, for example:

```javascript
render() {
   var isSelected = observable(() => selectedItem === this.props.item)
   if (isSelected()) {
     // do something
   }
}
```

You will notice if you add a debugger statement, that changing selectedItem will cause the `isSelected` observable to re-evaluate, but the `render` (which is the expensive one) will no longer be evaluated.

Since instantiating and inspecting observables on the fly is quite a common pattern, there is a convenience method for it, `expr(function)` (sugar for `observable(function)()`) so that you can write the above as 

```javascript
render() {
   if (expr(() => selectedItem === this.props.item)) {
      // item of this component is selected
   }
```

I hope that answers your question! Otherwise just let me know

**Comment by Kosta-Github** [comment]
OK, thanks for the quick help.

Yes, I can confirm that adding `mobs.expr()` like this in the example above produces the desired output:
```JavaScript
    const track = (len) => mobs.expr(() => (v().length === len));
```

Your lib is incredible!
