### ISSUE TITLE
Illegal state error - only data values can be readied while in transaction

### ISSUE THREAD

**Issue by thunderkid** [mweststrate/mobservable#97]
Hi, I just got this error and it's asking me to file a bug with stacktrace. So here it is:

```Uncaught Error: [mobservable] Illegal state; only data values can be readied while in transaction. Please file a bug with stacktrace.```

```

DataNode.markReady @ dnode.js:105
ViewNode.computeNextState @ dnode.js:214
ViewNode.wakeUp @ dnode.js:175
ObservableView.get @ observableview.js:42
Object.defineProperty.get @ observableobject.js:57
(anonymous function) @ quakeTableDetailReact.tsx:521
SimpleEventEmitter.emit @ simpleeventemitter.js:17
Object.defineProperty.set @ observableobject.js:62
ListVModelMasterObservable.setSelectedId @ listViewModelObservable.ts:182
ListVModelMasterObservable.clear @ listViewModelObservable.ts:156
ListDataModelObservable.setDataCore @ listDataModelObservable.ts:57
(anonymous function) @ quakeTableDetailReact.tsx:66
transaction @ dnode.js:28
DataModel.setExtendedData @ quakeTableDetailReact.tsx:63
(anonymous function) @ quakeTableDetailReact.tsx:270
Talker.processHoot @ talker.ts:26
(anonymous function) @ talker.ts:11
(anonymous function) @ talker.ts:43
fire @ jquery.js:3100
self.fireWith @ jquery.js:3212
done @ jquery.js:8265
(anonymous function) @ jquery.js:8606
```

I'm still debugging my own code so it's too messy to post a simplified version right now. I'm just obeying your stacktrace request without delay ...

**Comment by mweststrate** [comment]
Thanks for reporting! Which version of mobservable (and mobservable-react
if applicable) are you using?

**Comment by thunderkid** [comment]
I am using:
```
    "mobservable": "^1.2.1",
    "mobservable-react": "^2.1.1",
```
Problem seemed to be caused by an observable getter in one class (my ViewModel) wrapping an observable property in another class (my Model).

**Comment by mweststrate** [comment]
I analyzed your stacktrace and the use case is valid. Can you verify whether version `1.2.3` indeed fixes the issue?

**Comment by thunderkid** [comment]
Well, version 1.2.3 stops the error from appearing in the log, but it still isn't observing as I'd expect. I basically have this:
```

interface GeoBox {
    latSW: number,
    lngSW: number,
    latNE: number,
    lngNE: number
}

class DataModel {
    @observable
    geoBox: GeoBox; 
}

class ViewModel {
    model: DataModel;

    @observable
    get geoBox(): GeoBox {
        return this.model.geoBox;
    }
}

class MapView extends React.Component<{ vMod: ViewModel }, {}> {
    componentDidMount() {
        var vMod = this.props.vMod;

        var goodDisposer = observe(vMod.model, (change) => {
            console.log('good observer sees '+ change.name);
        }

        var badDisposer = observe(vMod, (change) => {
            console.log('bad observer sees '+change.name);
        }
    }
}

```

When I make changes to `DataModel.geoBox`, the good observer logs the changes correctly, but the bad observer doesn't. The bad observer just sees a change initially, then nothing afterwards. I think it should always see changes. Isn't that the point of a get observer?
(Making `GeoBox` into a class with `@observable` in front of each property doesn't help either.)

**Comment by mweststrate** [comment]
The behavior you see is as intended; the `observe` method only observes the object you pass in, it doesn't do deep observing.

So `observe(vMod, ...)` will observe changes like `vMod.model = { a new object }` but it won't observe a change like `vMod.model.latSW`, because the latter won't modify `.model` itself; its still the same pointer.

If you want to deep observe, use `autorun` instead (which is in any case way more powerful, `observe` is quite a low level primitive). The following snippet will 'deep' observe as both the `.model` and the `.latSW` observable will be observed (or any of the other observables if you would JSON.stringify the thing for example):

```javascript
var reallyGoodDisposer = autorun(() => {
   console.log(vMod.model.latSW);
});
```

When you start combining `autorun` and React components, I recommend to use the `@observer` annotation from the `mobservable-react` package, it does all the plumbing for you as it wraps the `.render()` method in a `autorun` and disposes the stuff when needed, sou you could just build your `MapView` like:

```javascript
@observer
class MapView extends React.Component<{ vMod: ViewModel }, {}> {
    render() {
        var vMod = this.props.vMod;
        return <span>vMod.model.latSW</span>
   }
}
```
